workers: 6
display: 100
epoches: 100
test_epoches: 500
batch_size: 128
base_lr: 0.0002
beta1: 0.5
ano_para: 0.1
#dataset: 'celebA'
#dataset: 'mnist'
#dataset: 'cifar10'
dataset: 'malware'
image_size: 128 
z_dim: 100
c_dim: 1
gf_dim: 128
df_dim: 128
#class_num: 10
class_num: 25